test_that("the browser records Shiny error payloads", {
  skip_on_cran()
  app <- local_app_driver(test_path("apps", "errors"), name = "error-payload")
  app$wait_for_js("window.bonesErrors && window.bonesErrors.safe_error !== undefined")
  errors <- app$get_js("window.bonesErrors")
  expect_equal(errors$silent$message, "")
  expect_equal(errors$validation$message, "pick one")
  expect_equal(errors$first_error$message, "boom")
  expect_contains(unlist(errors$silent$type), "validation")
  expect_contains(unlist(errors$validation$type), "validation")
  expect_null(errors$first_error$type)
  expect_equal(errors$safe_error$type, "shiny.custom.error")
  expect_equal(errors$safe_error$message, "safe boom")
})
